version: "3.1"

services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongo-server
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root # Change this as you wish
      MONGO_INITDB_ROOT_PASSWORD: admin # Change this as you wish
      MONGO_INITDB_DATABASE: dtmoney # Change this as you wish

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-server
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
